OCAMLMAKEFILE = OCamlMakefile
OCAMLYACC = menhir

PACKS = jsonm

SOURCES = common_types.ml loc.ml expr.ml value.ml json.ml \
	  ast.ml parser.mly lexer.mll lp.ml generate.mli \
	  generate.ml main.ml

RESULT  = main

include $(OCAMLMAKEFILE)
