OCAMLMAKEFILE = OCamlMakefile
OCAMLYACC = menhir

PACKS = jsonm

SOURCES = common_types.ml loc.ml expr.ml lp.ml value.ml json_value.ml \
	  ast.ml parser.mly lexer.mll generate.mli \
	  generate.ml main.ml

RESULT  = main

include $(OCAMLMAKEFILE)
